spring:
  application:
    name: trading-execution-engine
  datasource:
    url: jdbc:postgresql://db.ounknxatuppuztklyvyn.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: S@tgurukunj121

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

trading:
  capital: 500000
  risk-percent: 1
  threshold-percent: 1